### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by don-vip** [yopaseopor/traffic_signs_style_JOSM#1]
**MapPaint Style:**
icon "traffic_signs/BE/BE_A1a.png" not found.
icon "traffic_signs/BE/BE_A1b.png" not found.
icon "traffic_signs/BE/BE_A1c.png" not found.
icon "traffic_signs/BE/BE_A1d.png" not found.
icon "traffic_signs/BE/BE_A3.png" not found.
icon "traffic_signs/BE/BE_A5.png" not found.
icon "traffic_signs/BE/BE_B3.png" not found.
icon "traffic_signs/BE/BE_B7.png" not found.
icon "traffic_signs/BE/BE_B13.png" not found.
icon "traffic_signs/BE/BE_B15.png" not found.
icon "traffic_signs/BE/BE_C6.png" not found.
icon "traffic_signs/BE/BE_C24a.png" not found.
icon "traffic_signs/BE/BE_C24b.png" not found.
icon "traffic_signs/BE/BE_C24c.png" not found.
icon "traffic_signs/BE/BE_C31.png" not found.

**Presets:**
Could not get presets icon CAT_radar.png,

**Comment by yopaseopor** [comment]
Checked and added
