### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by don-vip** [yopaseopor/traffic_signs_style_JOSM#2]
Some icons are still missing:

**Style:**
icon "traffic_signs/BE/BE_B13.png" not found.

**Presets:**
Beacon right tertiary: Could not get presets icon traffic_signs/ES/ES_panel_dir_left_3.png
Beacon left highway: Could not get presets icon traffic_signs/ES/ES_panel_dir_left_2.png
Beacon left motorway: Could not get presets icon traffic_signs/ES/ES_panel_dir_left.png

**Comment by yopaseopor** [comment]
Checked and added
