### ISSUE TITLE
Icons still missing

### ISSUE THREAD

**Issue by don-vip** [yopaseopor/traffic_signs_style_JOSM#4]
It's still not OK. The new hosting on Github is not as convenient as before as we can't fix the errors ourselves anymore:

**Style:**
icon "traffic_signs/BE/BE_B13.png" not found.

**Presets:**
Destination sign motorway: Could not get presets icon https://raw.githubusercontent.com/yopaseopor/traffic_signs_preset_JOSM/master/presets/guidepost.png

Can you please check our integration tests results after each change of the style and preset, and fix reported issues?

The results are available here:
https://josm.openstreetmap.de/jenkins/job/JOSM/lastCompletedBuild/testReport/

```
org.openstreetmap.josm.gui.preferences.map.MapPaintPreferenceTestIT.testValidityOfAvailableStyles
org.openstreetmap.josm.gui.preferences.map.TaggingPresetPreferenceTestIT.testValidityOfAvailablePresets

```

**Comment by yopaseopor** [comment]
I know Github is not the best hosting for a JOSM preset or style .But with the "localization" for European countries preset and style will exceed the size limit, so I had to change it :( I try to do the best I could. I "recopy" all the icons to other folders to avoid errors. I continue with it.

**Comment by don-vip** [comment]
the style errors are gone. 3 new with presets, now:
1. Left then right curve: Could not get presets icon https://raw.githubusercontent.com/yopaseopor/traffic_signs_preset_JOSM/master/traffic_signs/BE/BE_A1c.png
2. Maximum gross weight: Could not get presets icon https://raw.githubusercontent.com/yopaseopor/traffic_signs_preset_JOSM/master/traffic_signs/BE/C21.png
3. Left curve: Could not get presets icon https://raw.githubusercontent.com/yopaseopor/traffic_signs_preset_JOSM/master/traffic_signs/BE/BE_A1a.png

**Comment by don-vip** [comment]
Only one to go:
1. Maximum gross weight: Could not get presets icon https://raw.githubusercontent.com/yopaseopor/traffic_signs_preset_JOSM/master/traffic_signs/BE/C21.png

**Comment by yopaseopor** [comment]
Thank you so much for your help. I hope it will useful.

**Comment by don-vip** [comment]
it's working now! thanks :)

**Comment by yopaseopor** [comment]
Thank you for your help ^_^

**Comment by don-vip** [comment]
New batch of problems:

**Style:**
1. icon "traffic_signs/BE/BE_D3.png" not found
2. icon "traffic_signs/BE/BE_D9.png" not found

**Presets**
1. lineNumber: 1; columnNumber: 1; Content is not allowed in prolog ==> file is invalid

**Comment by yopaseopor** [comment]
For preset
Sorry, but I don't understand how to deal with this error (I understand the consequences but I don't know how or where can I fix it).

**Comment by don-vip** [comment]
The file must have been corrupted somewhat. Did you change you workflow, tools, something?

**Comment by yopaseopor** [comment]
No, I only have updated via Github Windows software

**Comment by yopaseopor** [comment]
Now I fix the xml corrupt file but I don't find content issue so I have deleted all img content. It would be useful JOSM informs which line has the problem. The actual warning has no concret information about that

**Comment by don-vip** [comment]
I will see if I can add line number, but that's not necessarily easy. Here's the new batch of errors:
1. Failed to locate image 'https://raw.githubusercontent.com/yopaseopor/traffic_signs_preset_JOSM/master/traffic_signs/ES/BE_C31_RIGHT.png'
2. Failed to locate image 'https://raw.githubusercontent.com/yopaseopor/traffic_signs_preset_JOSM/master/traffic_signs/BE/BE_C37_LEFT.png'

**Comment by yopaseopor** [comment]
I know it will not be easy. It is a wish. Icons fixed, thank you for your help

**Comment by don-vip** [comment]
It would be easier to write a dedicated test in the Github project itself, and to enable it in https://travis-ci.org/ so you could have test results automatically, and with a greater precision (line numbers). I don't see how to add this information in the JOSM test.

**Comment by don-vip** [comment]
New batch:
1. "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/BE/BE_A1a.png" not found., 
2. "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/BE/BE_A1b.png" not found., 
3. "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/BE/BE_A1c.png" not found., 
4. "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/BE/BE_A1d.png" not found., 
5. "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/BE/BE_C24a.png" not found., 
6. "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/BE/BE_C24b.png" not found., 
7. "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/BE/BE_C24c.png" not found., 
8. "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/BE/BE_E9a.png" not found., 
9. "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/BE/BE_E9b.png" not found., 
10. "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/BE/BE_E9c.png" not found., 
11. "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/BE/BE_E9d.png" not found., 
12. "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/BE/BE_E9e.png" not found., 
13. "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/BE/BE_E9f.png" not found., 
14. "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/BE/BE_E9g.png" not found., 
15. "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/BE/BE_E9h.png" not found., 
16. "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/BE/BE_E9i.png" not found.

**Comment by yopaseopor** [comment]
Issue solved. Also we have new system to test errors in style and preset in Travis. I think it is a good idea you talk with @Xevib . Also thank you for your help.

**Comment by don-vip** [comment]
@Xevib you see how to test these issues ? A very small XML (for presets) and MapCSS (for style) parser that would fetch all icons to check their existence would be enough. Currently these errors are detected by JOSM integration test, but that's not really adequate for external styles that follow a fast pace of development: 
https://josm.openstreetmap.de/browser/josm/trunk/test/unit/org/openstreetmap/josm/gui/preferences/map/MapPaintPreferenceTestIT.java#L51
https://josm.openstreetmap.de/browser/josm/trunk/test/unit/org/openstreetmap/josm/gui/preferences/map/TaggingPresetPreferenceTestIT.java#L46

**Comment by Xevib** [comment]
@don-vip the XML & CSS tests can be extended to ensure that all the files are included on the style/presset. I think I will be able to check this without problems

**Comment by don-vip** [comment]
New batch:
1. End of Road reserved for pedestrians (segregated): Could not get presets icon https://raw.githubusercontent.com/yopaseopor/traffic_signs_preset_JOSM/master/traffic_signs/BE/BE_F101b_FOOT.png
2. End of Road reserved for horses,pedestrians and bicycles (segregated): Could not get presets icon https://raw.githubusercontent.com/yopaseopor/traffic_signs_preset_JOSM/master/traffic_signs/BE/BE_F101b_FOOT_BICYCLE_HORSE.png
3. Road reserved for horses,pedestrians and bicycles (segregated): Could not get presets icon https://raw.githubusercontent.com/yopaseopor/traffic_signs_preset_JOSM/master/traffic_signs/BE/BE_F99b_FOOT_BICYCLE_HORSE.png

**Comment by Xevib** [comment]
@don-vip I'm trying to improve the Travis script making that work without any user change. Where I can find how JOSM selects the xml file? It uses an regexp or takes the first xml file on the folder?

Thank yo

**Comment by don-vip** [comment]
Presets consis of a single XML file. JOSM fetches files listed there:
https://josm.openstreetmap.de/wiki/PresetsSource

On this page we have a link to:
https://raw.githubusercontent.com/yopaseopor/traffic_signs_preset_JOSM/master/Presets_Traffic_signs.zip

which contains a single file:
https://github.com/yopaseopor/traffic_signs_preset_JOSM/blob/master/Presets_Traffic_signs-preset.xml

**Comment by don-vip** [comment]
Any update please? Having JOSM unit tests failing for several days is not a comfortable situation, if the preset/style cannot be stabilized, we'll be forced to ignore them in our integration tests, I'd like to avoid that.

**Comment by yopaseopor** [comment]
Sorry for the delay. I am not a programmer and with "internationalization"
this is growing so fast: from more than 250 of only Spain (finished with
old scheme) to more than 2800 of 25 countries (and then multiply it by two)
. I have exceed all the JOSM wiki limits and had to move all to other
platform. I try the best I could. Now I am doing the second country:
Belgium. Please do not ignore the preset and the style. I think all of
these will be important in near future.

**Comment by Klumbumbus** [comment]
See also the [comment by stoecker](https://josm.openstreetmap.de/ticket/12860#comment:1): the zip file which is linked at https://josm.openstreetmap.de/wiki/PresetsSource should contain the icons (in subfolders if you wish) and the xml file only the path relative to the zip file, no whole URLs (e.g. "BE/BE_F101b_FOOT.png").

**Comment by don-vip** [comment]
New error: https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/BE/BE_B5.png not found

**Comment by don-vip** [comment]
Mmm, seems fixed :)

**Comment by yopaseopor** [comment]
I am making little changes. Now Style recognise 10 most mapped traffic
signs . Also I know I have problems with content error in preset (I had put
the urls for some reason I remembered today). Tomorrow I will try to fix it
after work.
Thank you for your pacience

**Comment by don-vip** [comment]
Still following errors:

Style:
icon "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/BE/BE_F45b.png" not found
icon "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/DE/DE/DE_274.1[30].png" not found
icon "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/DE/DE/DE_274[30].svg" not found
icon "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/DE/DE/DE_274[70].svg" not found

Presets:
SAXParseException; lineNumber: 691; columnNumber: 171; cvc-enumeration-valid: Value '' is not facet-valid with respect to enumeration '[on, off]'. It must be a value from the enumeration.

Any news regarding tests? The proper way is not to link development files directly to JOSM wiki, but rather add tests on this repository, make proper Github releases once all tests are OK, then update the release link on JOSM wiki. This will allow you to update styles/presets at your pace without breaking everything in our integration tests.

We are glad to help, but I hope you understand we cannot spend all our free time to debug missing icons.

**Comment by yopaseopor** [comment]
@xevib is working on it. He tries to make it better as soon as he can ( I
don't know anything about programming so... he helps me. I will never be
able to return him all his time and efforts he dedicates to help me).

-I don't know why value_off has to be wrong...if this works... (because
without value_off the behavour of the option is not correct
(traffic_signs:forward or traffic_signs:backward). But if this has to be
erased I will clean it.

-I put it all online...to test all the process. It is easy to test and fix
a missing icon because of the case sensitive policy of Github that breaks
me up sometimes the work (other times is my way of working too fast with
some errorsI). But it is so difficult to test an error JOSM does not tell
you locally where is the error, in 53810 lines (style) or 20907 lines
(preset), with 25 countries and +2800 items, with a generic message
"Content is not allowed in prolog" (what content? in what file?)
After 51 manual test,more than 25 hours, changing , checking and reviewing
the "correct XML", doing and doing all the possible test (deleting folders,
deleting files) to discover...JOSM or JAVA or github does not like
non-english characters (in UTF-8 era ¬¬u).

-At least this time it is not fair to talk me about lost time for debuggin
missing icons. Traffic signs is one of the biggest (in size, nor in use, I
know) preset of JOSM, it took a lot of hours of my spare time (I know I do
it because I like it, because I like JOSM and because I like traffic signs)
, trying to implement  an easy way to get traffic signs to every user of
OSM -Europe now, USA later?- . I'm glad to do it, but I hope you understand
all this efforts are big . I do the best I could. Sorry for not being so
good enough for JOSM.

-It has not been an easy road. First I had to change style to other format
so different (remember I am not a programmer so it was...a nightmare) ,
because JOSM, need it. Then I have to export it to github because of the
limits JOSM wiki has (no, I will not make four different zips to make
available all the files), and now I have problems with preset integrity
because of problems with non-english characters in JOSM/JAVA/github (I
don't know which part fails). I pass all these difficulties. Please, don't
ignore that.

-Thank you @xevib for your efforts and your help when I had to pass some
programming and test obstacles, and thank you other people of JOSM for
helping developing JOSM, and all addons are inside in.

**Comment by don-vip** [comment]
I know this is a lot of work :)

Only one error to go !

icon "https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/DE/DE_325.png" not found

**Comment by don-vip** [comment]
all tests are now ok !!! many thanks :+1:

**Comment by yopaseopor** [comment]
Soon I will try to make a big update with Austria, Belarus and Deutschland. Pray for me

**Comment by don-vip** [comment]
Only one error:
"https://raw.githubusercontent.com/yopaseopor/traffic_signs_style_JOSM/master/traffic_signs/FR/AB3a.png" not found

**Comment by don-vip** [comment]
@Xevib do you need help to write unit tests for this repository? I can help if needed. As I said, this is not JOSM's job to detect missing icons, so I am going to disable checks on JOSM integration tests until tests are available here.

**Comment by Klumbumbus** [comment]
There are some new icon problems:
https://josm.openstreetmap.de/jenkins/job/JOSM/1518/jdk=JDK8/testReport/org.openstreetmap.josm.gui.preferences.map/MapPaintPreferenceTestIT/testValidityOfAvailableStyles/

**Comment by Klumbumbus** [comment]
OK, fixed :)

**Comment by Klumbumbus** [comment]
Current missing icons:

SEVERE: Failed to locate image 'traffic_signs/DE/DE_274-70.svg'
Sep 21, 2016 8:29:18 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/DE/DE_274-70.svg" not found.
Sep 21, 2016 8:29:18 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/DE/DE_274-70.svg'
Sep 21, 2016 8:29:18 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/DE/DE_274-70.svg" not found.
Sep 21, 2016 8:29:18 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/DE/DE_274-70.svg'
Sep 21, 2016 8:29:18 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/DE/DE_274-70.svg" not found.
Sep 21, 2016 8:29:18 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/DE/DE_274-70.svg'
Sep 21, 2016 8:29:18 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/DE/DE_274-70.svg" not found.
Sep 21, 2016 8:29:18 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/DE/DE_274-70.svg'
Sep 21, 2016 8:29:18 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/DE/DE_274-70.svg" not found.
Sep 21, 2016 8:29:18 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/DE/DE_274-70.svg'
Sep 21, 2016 8:29:18 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/DE/DE_274-70.svg" not found.
Sep 21, 2016 8:29:18 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/DE/DE_274-70.svg'
Sep 21, 2016 8:29:18 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/DE/DE_274-70.svg" not found.
Sep 21, 2016 8:30:35 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:30:35 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:30:53 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:30:53 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
Sep 21, 2016 8:30:59 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:30:59 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:30:59 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:30:59 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
Sep 21, 2016 8:30:59 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:30:59 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/BE/BE_A7_up.png'
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/BE/BE_A7_up.png" not found.
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:31:00 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/BE/BE_A7_up.png'
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/BE/BE_A7_up.png" not found.
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:31:01 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
Sep 21, 2016 8:31:02 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/BE/BE_A7_up.png'
Sep 21, 2016 8:31:02 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/BE/BE_A7_up.png" not found.
Sep 21, 2016 8:31:02 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:31:02 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:31:02 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:31:02 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
Sep 21, 2016 8:31:02 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/BE/BE_A7_up.png'
Sep 21, 2016 8:31:02 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/BE/BE_A7_up.png" not found.
Sep 21, 2016 8:31:02 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/IR/IS-H01.11.png'
Sep 21, 2016 8:31:02 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/IR/IS-H01.11.png" not found.
Sep 21, 2016 8:31:02 PM org.openstreetmap.josm.Main error
SEVERE: Failed to locate image 'traffic_signs/SE/SE_J1_1.png'
Sep 21, 2016 8:31:02 PM org.openstreetmap.josm.Main warn
WARNING: Mappaint style "standard" (Traffic Signs) icon "traffic_signs/SE/SE_J1_1.png" not found.
